name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish to PyPI (Trusted Publishing)
      id: trusted-publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true
      continue-on-error: true

    - name: Publish to PyPI (API Token Fallback)
      if: failure() && steps.trusted-publish.outcome == 'failure'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        print-hash: true

    - name: Debug Trusted Publishing Failure
      if: failure() && steps.trusted-publish.outcome == 'failure'
      run: |
        echo "Trusted Publishing failed. This is likely due to:"
        echo "1. PyPI trusted publisher not configured for tags"
        echo "2. Environment name mismatch"
        echo "3. Repository name mismatch"
        echo ""
        echo "Current claims from GitHub:"
        echo "Repository: leshchenko1979/fast-mcp-telegram"
        echo "Environment: release"
        echo "Workflow: .github/workflows/publish.yml"
        echo "Ref: ${{ github.ref }}"
        echo ""
        echo "Make sure PyPI trusted publisher matches these values."
        echo "If publishing on tags, configure PyPI for 'refs/tags/*' instead of 'refs/heads/main'"
