name: Manual Publish to PyPI

# Manual workflow that bypasses Trusted Publishing and uses API tokens directly
# Use this when Trusted Publishing has configuration issues

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty for latest)'
        required: false
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* --verbose
